// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.32.1
// source: task_service.proto

package task_service

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TaskStatus int32

const (
	TaskStatus_TASK_STATUS_NEW      TaskStatus = 0
	TaskStatus_TASK_STATUS_FINISHED TaskStatus = 1
)

// Enum value maps for TaskStatus.
var (
	TaskStatus_name = map[int32]string{
		0: "TASK_STATUS_NEW",
		1: "TASK_STATUS_FINISHED",
	}
	TaskStatus_value = map[string]int32{
		"TASK_STATUS_NEW":      0,
		"TASK_STATUS_FINISHED": 1,
	}
)

func (x TaskStatus) Enum() *TaskStatus {
	p := new(TaskStatus)
	*p = x
	return p
}

func (x TaskStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TaskStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_task_service_proto_enumTypes[0].Descriptor()
}

func (TaskStatus) Type() protoreflect.EnumType {
	return &file_task_service_proto_enumTypes[0]
}

func (x TaskStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TaskStatus.Descriptor instead.
func (TaskStatus) EnumDescriptor() ([]byte, []int) {
	return file_task_service_proto_rawDescGZIP(), []int{0}
}

type CreateTaskRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Task          *Task                  `protobuf:"bytes,1,opt,name=task,proto3" json:"task,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateTaskRequest) Reset() {
	*x = CreateTaskRequest{}
	mi := &file_task_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTaskRequest) ProtoMessage() {}

func (x *CreateTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_task_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTaskRequest.ProtoReflect.Descriptor instead.
func (*CreateTaskRequest) Descriptor() ([]byte, []int) {
	return file_task_service_proto_rawDescGZIP(), []int{0}
}

func (x *CreateTaskRequest) GetTask() *Task {
	if x != nil {
		return x.Task
	}
	return nil
}

type CreateTaskResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskUUID      string                 `protobuf:"bytes,1,opt,name=TaskUUID,proto3" json:"TaskUUID,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateTaskResponse) Reset() {
	*x = CreateTaskResponse{}
	mi := &file_task_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTaskResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTaskResponse) ProtoMessage() {}

func (x *CreateTaskResponse) ProtoReflect() protoreflect.Message {
	mi := &file_task_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTaskResponse.ProtoReflect.Descriptor instead.
func (*CreateTaskResponse) Descriptor() ([]byte, []int) {
	return file_task_service_proto_rawDescGZIP(), []int{1}
}

func (x *CreateTaskResponse) GetTaskUUID() string {
	if x != nil {
		return x.TaskUUID
	}
	return ""
}

type FinishTaskRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskUUID      string                 `protobuf:"bytes,1,opt,name=taskUUID,proto3" json:"taskUUID,omitempty"`
	UserUUID      string                 `protobuf:"bytes,2,opt,name=userUUID,proto3" json:"userUUID,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FinishTaskRequest) Reset() {
	*x = FinishTaskRequest{}
	mi := &file_task_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FinishTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FinishTaskRequest) ProtoMessage() {}

func (x *FinishTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_task_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FinishTaskRequest.ProtoReflect.Descriptor instead.
func (*FinishTaskRequest) Descriptor() ([]byte, []int) {
	return file_task_service_proto_rawDescGZIP(), []int{2}
}

func (x *FinishTaskRequest) GetTaskUUID() string {
	if x != nil {
		return x.TaskUUID
	}
	return ""
}

func (x *FinishTaskRequest) GetUserUUID() string {
	if x != nil {
		return x.UserUUID
	}
	return ""
}

type DeleteTaskRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskUUID      string                 `protobuf:"bytes,1,opt,name=taskUUID,proto3" json:"taskUUID,omitempty"`
	UserUUID      string                 `protobuf:"bytes,2,opt,name=userUUID,proto3" json:"userUUID,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteTaskRequest) Reset() {
	*x = DeleteTaskRequest{}
	mi := &file_task_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteTaskRequest) ProtoMessage() {}

func (x *DeleteTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_task_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteTaskRequest.ProtoReflect.Descriptor instead.
func (*DeleteTaskRequest) Descriptor() ([]byte, []int) {
	return file_task_service_proto_rawDescGZIP(), []int{3}
}

func (x *DeleteTaskRequest) GetTaskUUID() string {
	if x != nil {
		return x.TaskUUID
	}
	return ""
}

func (x *DeleteTaskRequest) GetUserUUID() string {
	if x != nil {
		return x.UserUUID
	}
	return ""
}

type GetTaskRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskUUID      string                 `protobuf:"bytes,1,opt,name=taskUUID,proto3" json:"taskUUID,omitempty"`
	UserUUID      string                 `protobuf:"bytes,2,opt,name=userUUID,proto3" json:"userUUID,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTaskRequest) Reset() {
	*x = GetTaskRequest{}
	mi := &file_task_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTaskRequest) ProtoMessage() {}

func (x *GetTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_task_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTaskRequest.ProtoReflect.Descriptor instead.
func (*GetTaskRequest) Descriptor() ([]byte, []int) {
	return file_task_service_proto_rawDescGZIP(), []int{4}
}

func (x *GetTaskRequest) GetTaskUUID() string {
	if x != nil {
		return x.TaskUUID
	}
	return ""
}

func (x *GetTaskRequest) GetUserUUID() string {
	if x != nil {
		return x.UserUUID
	}
	return ""
}

type GetTaskResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Task          *Task                  `protobuf:"bytes,1,opt,name=task,proto3" json:"task,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTaskResponse) Reset() {
	*x = GetTaskResponse{}
	mi := &file_task_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTaskResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTaskResponse) ProtoMessage() {}

func (x *GetTaskResponse) ProtoReflect() protoreflect.Message {
	mi := &file_task_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTaskResponse.ProtoReflect.Descriptor instead.
func (*GetTaskResponse) Descriptor() ([]byte, []int) {
	return file_task_service_proto_rawDescGZIP(), []int{5}
}

func (x *GetTaskResponse) GetTask() *Task {
	if x != nil {
		return x.Task
	}
	return nil
}

type GetListOfTasksResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tasks         []*Task                `protobuf:"bytes,1,rep,name=tasks,proto3" json:"tasks,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetListOfTasksResponse) Reset() {
	*x = GetListOfTasksResponse{}
	mi := &file_task_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetListOfTasksResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetListOfTasksResponse) ProtoMessage() {}

func (x *GetListOfTasksResponse) ProtoReflect() protoreflect.Message {
	mi := &file_task_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetListOfTasksResponse.ProtoReflect.Descriptor instead.
func (*GetListOfTasksResponse) Descriptor() ([]byte, []int) {
	return file_task_service_proto_rawDescGZIP(), []int{6}
}

func (x *GetListOfTasksResponse) GetTasks() []*Task {
	if x != nil {
		return x.Tasks
	}
	return nil
}

type GetListOfTasksRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserUUID      string                 `protobuf:"bytes,1,opt,name=userUUID,proto3" json:"userUUID,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetListOfTasksRequest) Reset() {
	*x = GetListOfTasksRequest{}
	mi := &file_task_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetListOfTasksRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetListOfTasksRequest) ProtoMessage() {}

func (x *GetListOfTasksRequest) ProtoReflect() protoreflect.Message {
	mi := &file_task_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetListOfTasksRequest.ProtoReflect.Descriptor instead.
func (*GetListOfTasksRequest) Descriptor() ([]byte, []int) {
	return file_task_service_proto_rawDescGZIP(), []int{7}
}

func (x *GetListOfTasksRequest) GetUserUUID() string {
	if x != nil {
		return x.UserUUID
	}
	return ""
}

type Task struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskUUID      string                 `protobuf:"bytes,1,opt,name=TaskUUID,proto3" json:"TaskUUID,omitempty"`
	UserUUID      string                 `protobuf:"bytes,2,opt,name=UserUUID,proto3" json:"UserUUID,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=Description,proto3" json:"Description,omitempty"`
	Status        TaskStatus             `protobuf:"varint,4,opt,name=status,proto3,enum=pet_api.TaskStatus" json:"status,omitempty"`
	Title         string                 `protobuf:"bytes,5,opt,name=title,proto3" json:"title,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Task) Reset() {
	*x = Task{}
	mi := &file_task_service_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Task) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Task) ProtoMessage() {}

func (x *Task) ProtoReflect() protoreflect.Message {
	mi := &file_task_service_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Task.ProtoReflect.Descriptor instead.
func (*Task) Descriptor() ([]byte, []int) {
	return file_task_service_proto_rawDescGZIP(), []int{8}
}

func (x *Task) GetTaskUUID() string {
	if x != nil {
		return x.TaskUUID
	}
	return ""
}

func (x *Task) GetUserUUID() string {
	if x != nil {
		return x.UserUUID
	}
	return ""
}

func (x *Task) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Task) GetStatus() TaskStatus {
	if x != nil {
		return x.Status
	}
	return TaskStatus_TASK_STATUS_NEW
}

func (x *Task) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

var File_task_service_proto protoreflect.FileDescriptor

const file_task_service_proto_rawDesc = "" +
	"\n" +
	"\x12task_service.proto\x12\apet_api\x1a\vempty.proto\"6\n" +
	"\x11CreateTaskRequest\x12!\n" +
	"\x04task\x18\x01 \x01(\v2\r.pet_api.TaskR\x04task\"0\n" +
	"\x12CreateTaskResponse\x12\x1a\n" +
	"\bTaskUUID\x18\x01 \x01(\tR\bTaskUUID\"K\n" +
	"\x11FinishTaskRequest\x12\x1a\n" +
	"\btaskUUID\x18\x01 \x01(\tR\btaskUUID\x12\x1a\n" +
	"\buserUUID\x18\x02 \x01(\tR\buserUUID\"K\n" +
	"\x11DeleteTaskRequest\x12\x1a\n" +
	"\btaskUUID\x18\x01 \x01(\tR\btaskUUID\x12\x1a\n" +
	"\buserUUID\x18\x02 \x01(\tR\buserUUID\"H\n" +
	"\x0eGetTaskRequest\x12\x1a\n" +
	"\btaskUUID\x18\x01 \x01(\tR\btaskUUID\x12\x1a\n" +
	"\buserUUID\x18\x02 \x01(\tR\buserUUID\"4\n" +
	"\x0fGetTaskResponse\x12!\n" +
	"\x04task\x18\x01 \x01(\v2\r.pet_api.TaskR\x04task\"=\n" +
	"\x16GetListOfTasksResponse\x12#\n" +
	"\x05tasks\x18\x01 \x03(\v2\r.pet_api.TaskR\x05tasks\"3\n" +
	"\x15GetListOfTasksRequest\x12\x1a\n" +
	"\buserUUID\x18\x01 \x01(\tR\buserUUID\"\xa3\x01\n" +
	"\x04Task\x12\x1a\n" +
	"\bTaskUUID\x18\x01 \x01(\tR\bTaskUUID\x12\x1a\n" +
	"\bUserUUID\x18\x02 \x01(\tR\bUserUUID\x12 \n" +
	"\vDescription\x18\x03 \x01(\tR\vDescription\x12+\n" +
	"\x06status\x18\x04 \x01(\x0e2\x13.pet_api.TaskStatusR\x06status\x12\x14\n" +
	"\x05title\x18\x05 \x01(\tR\x05title*;\n" +
	"\n" +
	"TaskStatus\x12\x13\n" +
	"\x0fTASK_STATUS_NEW\x10\x00\x12\x18\n" +
	"\x14TASK_STATUS_FINISHED\x10\x012\xe9\x02\n" +
	"\vTaskService\x12E\n" +
	"\n" +
	"CreateTask\x12\x1a.pet_api.CreateTaskRequest\x1a\x1b.pet_api.CreateTaskResponse\x12@\n" +
	"\n" +
	"FinishTask\x12\x1a.pet_api.FinishTaskRequest\x1a\x16.google.protobuf.Empty\x12@\n" +
	"\n" +
	"DeleteTask\x12\x1a.pet_api.DeleteTaskRequest\x1a\x16.google.protobuf.Empty\x12<\n" +
	"\aGetTask\x12\x17.pet_api.GetTaskRequest\x1a\x18.pet_api.GetTaskResponse\x12Q\n" +
	"\x0eGetListOfTasks\x12\x1e.pet_api.GetListOfTasksRequest\x1a\x1f.pet_api.GetListOfTasksResponseB\x12Z\x10pkg/task_serviceb\x06proto3"

var (
	file_task_service_proto_rawDescOnce sync.Once
	file_task_service_proto_rawDescData []byte
)

func file_task_service_proto_rawDescGZIP() []byte {
	file_task_service_proto_rawDescOnce.Do(func() {
		file_task_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_task_service_proto_rawDesc), len(file_task_service_proto_rawDesc)))
	})
	return file_task_service_proto_rawDescData
}

var file_task_service_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_task_service_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_task_service_proto_goTypes = []any{
	(TaskStatus)(0),                // 0: pet_api.TaskStatus
	(*CreateTaskRequest)(nil),      // 1: pet_api.CreateTaskRequest
	(*CreateTaskResponse)(nil),     // 2: pet_api.CreateTaskResponse
	(*FinishTaskRequest)(nil),      // 3: pet_api.FinishTaskRequest
	(*DeleteTaskRequest)(nil),      // 4: pet_api.DeleteTaskRequest
	(*GetTaskRequest)(nil),         // 5: pet_api.GetTaskRequest
	(*GetTaskResponse)(nil),        // 6: pet_api.GetTaskResponse
	(*GetListOfTasksResponse)(nil), // 7: pet_api.GetListOfTasksResponse
	(*GetListOfTasksRequest)(nil),  // 8: pet_api.GetListOfTasksRequest
	(*Task)(nil),                   // 9: pet_api.Task
	(*emptypb.Empty)(nil),          // 10: google.protobuf.Empty
}
var file_task_service_proto_depIdxs = []int32{
	9,  // 0: pet_api.CreateTaskRequest.task:type_name -> pet_api.Task
	9,  // 1: pet_api.GetTaskResponse.task:type_name -> pet_api.Task
	9,  // 2: pet_api.GetListOfTasksResponse.tasks:type_name -> pet_api.Task
	0,  // 3: pet_api.Task.status:type_name -> pet_api.TaskStatus
	1,  // 4: pet_api.TaskService.CreateTask:input_type -> pet_api.CreateTaskRequest
	3,  // 5: pet_api.TaskService.FinishTask:input_type -> pet_api.FinishTaskRequest
	4,  // 6: pet_api.TaskService.DeleteTask:input_type -> pet_api.DeleteTaskRequest
	5,  // 7: pet_api.TaskService.GetTask:input_type -> pet_api.GetTaskRequest
	8,  // 8: pet_api.TaskService.GetListOfTasks:input_type -> pet_api.GetListOfTasksRequest
	2,  // 9: pet_api.TaskService.CreateTask:output_type -> pet_api.CreateTaskResponse
	10, // 10: pet_api.TaskService.FinishTask:output_type -> google.protobuf.Empty
	10, // 11: pet_api.TaskService.DeleteTask:output_type -> google.protobuf.Empty
	6,  // 12: pet_api.TaskService.GetTask:output_type -> pet_api.GetTaskResponse
	7,  // 13: pet_api.TaskService.GetListOfTasks:output_type -> pet_api.GetListOfTasksResponse
	9,  // [9:14] is the sub-list for method output_type
	4,  // [4:9] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_task_service_proto_init() }
func file_task_service_proto_init() {
	if File_task_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_task_service_proto_rawDesc), len(file_task_service_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_task_service_proto_goTypes,
		DependencyIndexes: file_task_service_proto_depIdxs,
		EnumInfos:         file_task_service_proto_enumTypes,
		MessageInfos:      file_task_service_proto_msgTypes,
	}.Build()
	File_task_service_proto = out.File
	file_task_service_proto_goTypes = nil
	file_task_service_proto_depIdxs = nil
}
