// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.32.1
// source: task_service.proto

package task_service

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Status int32

const (
	Status_STATUS_NEW      Status = 0
	Status_STATUS_FINISHED Status = 1
)

// Enum value maps for Status.
var (
	Status_name = map[int32]string{
		0: "STATUS_NEW",
		1: "STATUS_FINISHED",
	}
	Status_value = map[string]int32{
		"STATUS_NEW":      0,
		"STATUS_FINISHED": 1,
	}
)

func (x Status) Enum() *Status {
	p := new(Status)
	*p = x
	return p
}

func (x Status) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Status) Descriptor() protoreflect.EnumDescriptor {
	return file_task_service_proto_enumTypes[0].Descriptor()
}

func (Status) Type() protoreflect.EnumType {
	return &file_task_service_proto_enumTypes[0]
}

func (x Status) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Status.Descriptor instead.
func (Status) EnumDescriptor() ([]byte, []int) {
	return file_task_service_proto_rawDescGZIP(), []int{0}
}

type CreateTaskRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserID        string                 `protobuf:"bytes,1,opt,name=userID,proto3" json:"userID,omitempty"`
	Description   string                 `protobuf:"bytes,2,opt,name=Description,proto3" json:"Description,omitempty"`
	Status        Status                 `protobuf:"varint,3,opt,name=status,proto3,enum=pet_api.Status" json:"status,omitempty"`
	Title         string                 `protobuf:"bytes,4,opt,name=title,proto3" json:"title,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateTaskRequest) Reset() {
	*x = CreateTaskRequest{}
	mi := &file_task_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTaskRequest) ProtoMessage() {}

func (x *CreateTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_task_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTaskRequest.ProtoReflect.Descriptor instead.
func (*CreateTaskRequest) Descriptor() ([]byte, []int) {
	return file_task_service_proto_rawDescGZIP(), []int{0}
}

func (x *CreateTaskRequest) GetUserID() string {
	if x != nil {
		return x.UserID
	}
	return ""
}

func (x *CreateTaskRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CreateTaskRequest) GetStatus() Status {
	if x != nil {
		return x.Status
	}
	return Status_STATUS_NEW
}

func (x *CreateTaskRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

type CreateTaskResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ID            string                 `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateTaskResponse) Reset() {
	*x = CreateTaskResponse{}
	mi := &file_task_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTaskResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTaskResponse) ProtoMessage() {}

func (x *CreateTaskResponse) ProtoReflect() protoreflect.Message {
	mi := &file_task_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTaskResponse.ProtoReflect.Descriptor instead.
func (*CreateTaskResponse) Descriptor() ([]byte, []int) {
	return file_task_service_proto_rawDescGZIP(), []int{1}
}

func (x *CreateTaskResponse) GetID() string {
	if x != nil {
		return x.ID
	}
	return ""
}

type FinishTaskRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskID        string                 `protobuf:"bytes,1,opt,name=taskID,proto3" json:"taskID,omitempty"`
	UserID        string                 `protobuf:"bytes,2,opt,name=userID,proto3" json:"userID,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FinishTaskRequest) Reset() {
	*x = FinishTaskRequest{}
	mi := &file_task_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FinishTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FinishTaskRequest) ProtoMessage() {}

func (x *FinishTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_task_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FinishTaskRequest.ProtoReflect.Descriptor instead.
func (*FinishTaskRequest) Descriptor() ([]byte, []int) {
	return file_task_service_proto_rawDescGZIP(), []int{2}
}

func (x *FinishTaskRequest) GetTaskID() string {
	if x != nil {
		return x.TaskID
	}
	return ""
}

func (x *FinishTaskRequest) GetUserID() string {
	if x != nil {
		return x.UserID
	}
	return ""
}

type DeleteTaskRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskID        string                 `protobuf:"bytes,1,opt,name=taskID,proto3" json:"taskID,omitempty"`
	UserID        string                 `protobuf:"bytes,2,opt,name=userID,proto3" json:"userID,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteTaskRequest) Reset() {
	*x = DeleteTaskRequest{}
	mi := &file_task_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteTaskRequest) ProtoMessage() {}

func (x *DeleteTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_task_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteTaskRequest.ProtoReflect.Descriptor instead.
func (*DeleteTaskRequest) Descriptor() ([]byte, []int) {
	return file_task_service_proto_rawDescGZIP(), []int{3}
}

func (x *DeleteTaskRequest) GetTaskID() string {
	if x != nil {
		return x.TaskID
	}
	return ""
}

func (x *DeleteTaskRequest) GetUserID() string {
	if x != nil {
		return x.UserID
	}
	return ""
}

type GetTaskRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskID        string                 `protobuf:"bytes,1,opt,name=taskID,proto3" json:"taskID,omitempty"`
	UserID        string                 `protobuf:"bytes,2,opt,name=userID,proto3" json:"userID,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTaskRequest) Reset() {
	*x = GetTaskRequest{}
	mi := &file_task_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTaskRequest) ProtoMessage() {}

func (x *GetTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_task_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTaskRequest.ProtoReflect.Descriptor instead.
func (*GetTaskRequest) Descriptor() ([]byte, []int) {
	return file_task_service_proto_rawDescGZIP(), []int{4}
}

func (x *GetTaskRequest) GetTaskID() string {
	if x != nil {
		return x.TaskID
	}
	return ""
}

func (x *GetTaskRequest) GetUserID() string {
	if x != nil {
		return x.UserID
	}
	return ""
}

type GetTaskResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ID            string                 `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Description   string                 `protobuf:"bytes,2,opt,name=Description,proto3" json:"Description,omitempty"`
	Status        Status                 `protobuf:"varint,3,opt,name=status,proto3,enum=pet_api.Status" json:"status,omitempty"`
	Title         string                 `protobuf:"bytes,4,opt,name=title,proto3" json:"title,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTaskResponse) Reset() {
	*x = GetTaskResponse{}
	mi := &file_task_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTaskResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTaskResponse) ProtoMessage() {}

func (x *GetTaskResponse) ProtoReflect() protoreflect.Message {
	mi := &file_task_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTaskResponse.ProtoReflect.Descriptor instead.
func (*GetTaskResponse) Descriptor() ([]byte, []int) {
	return file_task_service_proto_rawDescGZIP(), []int{5}
}

func (x *GetTaskResponse) GetID() string {
	if x != nil {
		return x.ID
	}
	return ""
}

func (x *GetTaskResponse) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *GetTaskResponse) GetStatus() Status {
	if x != nil {
		return x.Status
	}
	return Status_STATUS_NEW
}

func (x *GetTaskResponse) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

type GetListOfTasksResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tasks         []*GetTaskResponse     `protobuf:"bytes,1,rep,name=tasks,proto3" json:"tasks,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetListOfTasksResponse) Reset() {
	*x = GetListOfTasksResponse{}
	mi := &file_task_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetListOfTasksResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetListOfTasksResponse) ProtoMessage() {}

func (x *GetListOfTasksResponse) ProtoReflect() protoreflect.Message {
	mi := &file_task_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetListOfTasksResponse.ProtoReflect.Descriptor instead.
func (*GetListOfTasksResponse) Descriptor() ([]byte, []int) {
	return file_task_service_proto_rawDescGZIP(), []int{6}
}

func (x *GetListOfTasksResponse) GetTasks() []*GetTaskResponse {
	if x != nil {
		return x.Tasks
	}
	return nil
}

type GetListOfTasksRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserID        string                 `protobuf:"bytes,1,opt,name=userID,proto3" json:"userID,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetListOfTasksRequest) Reset() {
	*x = GetListOfTasksRequest{}
	mi := &file_task_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetListOfTasksRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetListOfTasksRequest) ProtoMessage() {}

func (x *GetListOfTasksRequest) ProtoReflect() protoreflect.Message {
	mi := &file_task_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetListOfTasksRequest.ProtoReflect.Descriptor instead.
func (*GetListOfTasksRequest) Descriptor() ([]byte, []int) {
	return file_task_service_proto_rawDescGZIP(), []int{7}
}

func (x *GetListOfTasksRequest) GetUserID() string {
	if x != nil {
		return x.UserID
	}
	return ""
}

var File_task_service_proto protoreflect.FileDescriptor

const file_task_service_proto_rawDesc = "" +
	"\n" +
	"\x12task_service.proto\x12\apet_api\x1a\vempty.proto\"\x8c\x01\n" +
	"\x11CreateTaskRequest\x12\x16\n" +
	"\x06userID\x18\x01 \x01(\tR\x06userID\x12 \n" +
	"\vDescription\x18\x02 \x01(\tR\vDescription\x12'\n" +
	"\x06status\x18\x03 \x01(\x0e2\x0f.pet_api.StatusR\x06status\x12\x14\n" +
	"\x05title\x18\x04 \x01(\tR\x05title\"$\n" +
	"\x12CreateTaskResponse\x12\x0e\n" +
	"\x02ID\x18\x01 \x01(\tR\x02ID\"C\n" +
	"\x11FinishTaskRequest\x12\x16\n" +
	"\x06taskID\x18\x01 \x01(\tR\x06taskID\x12\x16\n" +
	"\x06userID\x18\x02 \x01(\tR\x06userID\"C\n" +
	"\x11DeleteTaskRequest\x12\x16\n" +
	"\x06taskID\x18\x01 \x01(\tR\x06taskID\x12\x16\n" +
	"\x06userID\x18\x02 \x01(\tR\x06userID\"@\n" +
	"\x0eGetTaskRequest\x12\x16\n" +
	"\x06taskID\x18\x01 \x01(\tR\x06taskID\x12\x16\n" +
	"\x06userID\x18\x02 \x01(\tR\x06userID\"\x82\x01\n" +
	"\x0fGetTaskResponse\x12\x0e\n" +
	"\x02ID\x18\x01 \x01(\tR\x02ID\x12 \n" +
	"\vDescription\x18\x02 \x01(\tR\vDescription\x12'\n" +
	"\x06status\x18\x03 \x01(\x0e2\x0f.pet_api.StatusR\x06status\x12\x14\n" +
	"\x05title\x18\x04 \x01(\tR\x05title\"H\n" +
	"\x16GetListOfTasksResponse\x12.\n" +
	"\x05tasks\x18\x01 \x03(\v2\x18.pet_api.GetTaskResponseR\x05tasks\"/\n" +
	"\x15GetListOfTasksRequest\x12\x16\n" +
	"\x06userID\x18\x01 \x01(\tR\x06userID*-\n" +
	"\x06Status\x12\x0e\n" +
	"\n" +
	"STATUS_NEW\x10\x00\x12\x13\n" +
	"\x0fSTATUS_FINISHED\x10\x012\xe9\x02\n" +
	"\vTaskService\x12E\n" +
	"\n" +
	"CreateTask\x12\x1a.pet_api.CreateTaskRequest\x1a\x1b.pet_api.CreateTaskResponse\x12@\n" +
	"\n" +
	"FinishTask\x12\x1a.pet_api.FinishTaskRequest\x1a\x16.google.protobuf.Empty\x12@\n" +
	"\n" +
	"DeleteTask\x12\x1a.pet_api.DeleteTaskRequest\x1a\x16.google.protobuf.Empty\x12<\n" +
	"\aGetTask\x12\x17.pet_api.GetTaskRequest\x1a\x18.pet_api.GetTaskResponse\x12Q\n" +
	"\x0eGetListOfTasks\x12\x1e.pet_api.GetListOfTasksRequest\x1a\x1f.pet_api.GetListOfTasksResponseB\x12Z\x10pkg/task_serviceb\x06proto3"

var (
	file_task_service_proto_rawDescOnce sync.Once
	file_task_service_proto_rawDescData []byte
)

func file_task_service_proto_rawDescGZIP() []byte {
	file_task_service_proto_rawDescOnce.Do(func() {
		file_task_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_task_service_proto_rawDesc), len(file_task_service_proto_rawDesc)))
	})
	return file_task_service_proto_rawDescData
}

var file_task_service_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_task_service_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_task_service_proto_goTypes = []any{
	(Status)(0),                    // 0: pet_api.Status
	(*CreateTaskRequest)(nil),      // 1: pet_api.CreateTaskRequest
	(*CreateTaskResponse)(nil),     // 2: pet_api.CreateTaskResponse
	(*FinishTaskRequest)(nil),      // 3: pet_api.FinishTaskRequest
	(*DeleteTaskRequest)(nil),      // 4: pet_api.DeleteTaskRequest
	(*GetTaskRequest)(nil),         // 5: pet_api.GetTaskRequest
	(*GetTaskResponse)(nil),        // 6: pet_api.GetTaskResponse
	(*GetListOfTasksResponse)(nil), // 7: pet_api.GetListOfTasksResponse
	(*GetListOfTasksRequest)(nil),  // 8: pet_api.GetListOfTasksRequest
	(*emptypb.Empty)(nil),          // 9: google.protobuf.Empty
}
var file_task_service_proto_depIdxs = []int32{
	0, // 0: pet_api.CreateTaskRequest.status:type_name -> pet_api.Status
	0, // 1: pet_api.GetTaskResponse.status:type_name -> pet_api.Status
	6, // 2: pet_api.GetListOfTasksResponse.tasks:type_name -> pet_api.GetTaskResponse
	1, // 3: pet_api.TaskService.CreateTask:input_type -> pet_api.CreateTaskRequest
	3, // 4: pet_api.TaskService.FinishTask:input_type -> pet_api.FinishTaskRequest
	4, // 5: pet_api.TaskService.DeleteTask:input_type -> pet_api.DeleteTaskRequest
	5, // 6: pet_api.TaskService.GetTask:input_type -> pet_api.GetTaskRequest
	8, // 7: pet_api.TaskService.GetListOfTasks:input_type -> pet_api.GetListOfTasksRequest
	2, // 8: pet_api.TaskService.CreateTask:output_type -> pet_api.CreateTaskResponse
	9, // 9: pet_api.TaskService.FinishTask:output_type -> google.protobuf.Empty
	9, // 10: pet_api.TaskService.DeleteTask:output_type -> google.protobuf.Empty
	6, // 11: pet_api.TaskService.GetTask:output_type -> pet_api.GetTaskResponse
	7, // 12: pet_api.TaskService.GetListOfTasks:output_type -> pet_api.GetListOfTasksResponse
	8, // [8:13] is the sub-list for method output_type
	3, // [3:8] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_task_service_proto_init() }
func file_task_service_proto_init() {
	if File_task_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_task_service_proto_rawDesc), len(file_task_service_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_task_service_proto_goTypes,
		DependencyIndexes: file_task_service_proto_depIdxs,
		EnumInfos:         file_task_service_proto_enumTypes,
		MessageInfos:      file_task_service_proto_msgTypes,
	}.Build()
	File_task_service_proto = out.File
	file_task_service_proto_goTypes = nil
	file_task_service_proto_depIdxs = nil
}
