// Code generated by ogen, DO NOT EDIT.

package openapi

import (
	"github.com/go-faster/errors"
	"github.com/google/uuid"
)

// Ref: #/components/schemas/CreateTaskResponse
type CreateTaskResponse struct {
	TaskUUID uuid.UUID `json:"task_uuid"`
}

// GetTaskUUID returns the value of TaskUUID.
func (s *CreateTaskResponse) GetTaskUUID() uuid.UUID {
	return s.TaskUUID
}

// SetTaskUUID sets the value of TaskUUID.
func (s *CreateTaskResponse) SetTaskUUID(val uuid.UUID) {
	s.TaskUUID = val
}

func (*CreateTaskResponse) handleCreateTaskRes() {}

// Ref: #/components/schemas/DeleteTaskRequest
type DeleteTaskRequest struct {
	TaskUUID uuid.UUID `json:"task_uuid"`
	UserUUID uuid.UUID `json:"user_uuid"`
}

// GetTaskUUID returns the value of TaskUUID.
func (s *DeleteTaskRequest) GetTaskUUID() uuid.UUID {
	return s.TaskUUID
}

// GetUserUUID returns the value of UserUUID.
func (s *DeleteTaskRequest) GetUserUUID() uuid.UUID {
	return s.UserUUID
}

// SetTaskUUID sets the value of TaskUUID.
func (s *DeleteTaskRequest) SetTaskUUID(val uuid.UUID) {
	s.TaskUUID = val
}

// SetUserUUID sets the value of UserUUID.
func (s *DeleteTaskRequest) SetUserUUID(val uuid.UUID) {
	s.UserUUID = val
}

// Ref: #/components/schemas/Error
type Error struct {
	Code    string `json:"code"`
	Message string `json:"message"`
}

// GetCode returns the value of Code.
func (s *Error) GetCode() string {
	return s.Code
}

// GetMessage returns the value of Message.
func (s *Error) GetMessage() string {
	return s.Message
}

// SetCode sets the value of Code.
func (s *Error) SetCode(val string) {
	s.Code = val
}

// SetMessage sets the value of Message.
func (s *Error) SetMessage(val string) {
	s.Message = val
}

// Ref: #/components/schemas/FinishTaskRequest
type FinishTaskRequest struct {
	UserUUID uuid.UUID `json:"user_uuid"`
	TaskUUID uuid.UUID `json:"task_uuid"`
}

// GetUserUUID returns the value of UserUUID.
func (s *FinishTaskRequest) GetUserUUID() uuid.UUID {
	return s.UserUUID
}

// GetTaskUUID returns the value of TaskUUID.
func (s *FinishTaskRequest) GetTaskUUID() uuid.UUID {
	return s.TaskUUID
}

// SetUserUUID sets the value of UserUUID.
func (s *FinishTaskRequest) SetUserUUID(val uuid.UUID) {
	s.UserUUID = val
}

// SetTaskUUID sets the value of TaskUUID.
func (s *FinishTaskRequest) SetTaskUUID(val uuid.UUID) {
	s.TaskUUID = val
}

// Ref: #/components/schemas/GetListOfTasksRequest
type GetListOfTasksRequest struct {
	UserUUID uuid.UUID `json:"user_uuid"`
}

// GetUserUUID returns the value of UserUUID.
func (s *GetListOfTasksRequest) GetUserUUID() uuid.UUID {
	return s.UserUUID
}

// SetUserUUID sets the value of UserUUID.
func (s *GetListOfTasksRequest) SetUserUUID(val uuid.UUID) {
	s.UserUUID = val
}

// Ref: #/components/schemas/GetListOfTasksResponse
type GetListOfTasksResponse struct {
	Tasks []Task `json:"tasks"`
}

// GetTasks returns the value of Tasks.
func (s *GetListOfTasksResponse) GetTasks() []Task {
	return s.Tasks
}

// SetTasks sets the value of Tasks.
func (s *GetListOfTasksResponse) SetTasks(val []Task) {
	s.Tasks = val
}

func (*GetListOfTasksResponse) handleGetListOfTasksRes() {}

// Ref: #/components/schemas/GetTaskRequest
type GetTaskRequest struct {
	TaskUUID uuid.UUID `json:"task_uuid"`
	UserUUID uuid.UUID `json:"user_uuid"`
}

// GetTaskUUID returns the value of TaskUUID.
func (s *GetTaskRequest) GetTaskUUID() uuid.UUID {
	return s.TaskUUID
}

// GetUserUUID returns the value of UserUUID.
func (s *GetTaskRequest) GetUserUUID() uuid.UUID {
	return s.UserUUID
}

// SetTaskUUID sets the value of TaskUUID.
func (s *GetTaskRequest) SetTaskUUID(val uuid.UUID) {
	s.TaskUUID = val
}

// SetUserUUID sets the value of UserUUID.
func (s *GetTaskRequest) SetUserUUID(val uuid.UUID) {
	s.UserUUID = val
}

type HandleCreateTaskBadRequest Error

func (*HandleCreateTaskBadRequest) handleCreateTaskRes() {}

type HandleCreateTaskInternalServerError Error

func (*HandleCreateTaskInternalServerError) handleCreateTaskRes() {}

type HandleDeleteTaskBadRequest Error

func (*HandleDeleteTaskBadRequest) handleDeleteTaskRes() {}

type HandleDeleteTaskInternalServerError Error

func (*HandleDeleteTaskInternalServerError) handleDeleteTaskRes() {}

// HandleDeleteTaskNoContent is response for HandleDeleteTask operation.
type HandleDeleteTaskNoContent struct{}

func (*HandleDeleteTaskNoContent) handleDeleteTaskRes() {}

type HandleDeleteTaskNotFound Error

func (*HandleDeleteTaskNotFound) handleDeleteTaskRes() {}

type HandleFinishTaskBadRequest Error

func (*HandleFinishTaskBadRequest) handleFinishTaskRes() {}

type HandleFinishTaskInternalServerError Error

func (*HandleFinishTaskInternalServerError) handleFinishTaskRes() {}

// HandleFinishTaskNoContent is response for HandleFinishTask operation.
type HandleFinishTaskNoContent struct{}

func (*HandleFinishTaskNoContent) handleFinishTaskRes() {}

type HandleFinishTaskNotFound Error

func (*HandleFinishTaskNotFound) handleFinishTaskRes() {}

type HandleGetListOfTasksBadRequest Error

func (*HandleGetListOfTasksBadRequest) handleGetListOfTasksRes() {}

type HandleGetListOfTasksInternalServerError Error

func (*HandleGetListOfTasksInternalServerError) handleGetListOfTasksRes() {}

type HandleGetListOfTasksNotFound Error

func (*HandleGetListOfTasksNotFound) handleGetListOfTasksRes() {}

type HandleGetTaskBadRequest Error

func (*HandleGetTaskBadRequest) handleGetTaskRes() {}

type HandleGetTaskInternalServerError Error

func (*HandleGetTaskInternalServerError) handleGetTaskRes() {}

type HandleGetTaskNotFound Error

func (*HandleGetTaskNotFound) handleGetTaskRes() {}

// NewOptNilUUID returns new OptNilUUID with value set to v.
func NewOptNilUUID(v uuid.UUID) OptNilUUID {
	return OptNilUUID{
		Value: v,
		Set:   true,
	}
}

// OptNilUUID is optional nullable uuid.UUID.
type OptNilUUID struct {
	Value uuid.UUID
	Set   bool
	Null  bool
}

// IsSet returns true if OptNilUUID was set.
func (o OptNilUUID) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptNilUUID) Reset() {
	var v uuid.UUID
	o.Value = v
	o.Set = false
	o.Null = false
}

// SetTo sets value to v.
func (o *OptNilUUID) SetTo(v uuid.UUID) {
	o.Set = true
	o.Null = false
	o.Value = v
}

// IsNull returns true if value is Null.
func (o OptNilUUID) IsNull() bool { return o.Null }

// SetToNull sets value to null.
func (o *OptNilUUID) SetToNull() {
	o.Set = true
	o.Null = true
	var v uuid.UUID
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptNilUUID) Get() (v uuid.UUID, ok bool) {
	if o.Null {
		return v, false
	}
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptNilUUID) Or(d uuid.UUID) uuid.UUID {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptString returns new OptString with value set to v.
func NewOptString(v string) OptString {
	return OptString{
		Value: v,
		Set:   true,
	}
}

// OptString is optional string.
type OptString struct {
	Value string
	Set   bool
}

// IsSet returns true if OptString was set.
func (o OptString) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptString) Reset() {
	var v string
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptString) SetTo(v string) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptString) Get() (v string, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptString) Or(d string) string {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptTaskStatus returns new OptTaskStatus with value set to v.
func NewOptTaskStatus(v TaskStatus) OptTaskStatus {
	return OptTaskStatus{
		Value: v,
		Set:   true,
	}
}

// OptTaskStatus is optional TaskStatus.
type OptTaskStatus struct {
	Value TaskStatus
	Set   bool
}

// IsSet returns true if OptTaskStatus was set.
func (o OptTaskStatus) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptTaskStatus) Reset() {
	var v TaskStatus
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptTaskStatus) SetTo(v TaskStatus) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptTaskStatus) Get() (v TaskStatus, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptTaskStatus) Or(d TaskStatus) TaskStatus {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptUUID returns new OptUUID with value set to v.
func NewOptUUID(v uuid.UUID) OptUUID {
	return OptUUID{
		Value: v,
		Set:   true,
	}
}

// OptUUID is optional uuid.UUID.
type OptUUID struct {
	Value uuid.UUID
	Set   bool
}

// IsSet returns true if OptUUID was set.
func (o OptUUID) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptUUID) Reset() {
	var v uuid.UUID
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptUUID) SetTo(v uuid.UUID) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptUUID) Get() (v uuid.UUID, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptUUID) Or(d uuid.UUID) uuid.UUID {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// Ref: #/components/schemas/Task
type Task struct {
	Description OptString     `json:"description"`
	Title       OptString     `json:"title"`
	Status      OptTaskStatus `json:"status"`
	TaskUUID    OptNilUUID    `json:"task_uuid"`
	UserUUID    OptUUID       `json:"user_uuid"`
}

// GetDescription returns the value of Description.
func (s *Task) GetDescription() OptString {
	return s.Description
}

// GetTitle returns the value of Title.
func (s *Task) GetTitle() OptString {
	return s.Title
}

// GetStatus returns the value of Status.
func (s *Task) GetStatus() OptTaskStatus {
	return s.Status
}

// GetTaskUUID returns the value of TaskUUID.
func (s *Task) GetTaskUUID() OptNilUUID {
	return s.TaskUUID
}

// GetUserUUID returns the value of UserUUID.
func (s *Task) GetUserUUID() OptUUID {
	return s.UserUUID
}

// SetDescription sets the value of Description.
func (s *Task) SetDescription(val OptString) {
	s.Description = val
}

// SetTitle sets the value of Title.
func (s *Task) SetTitle(val OptString) {
	s.Title = val
}

// SetStatus sets the value of Status.
func (s *Task) SetStatus(val OptTaskStatus) {
	s.Status = val
}

// SetTaskUUID sets the value of TaskUUID.
func (s *Task) SetTaskUUID(val OptNilUUID) {
	s.TaskUUID = val
}

// SetUserUUID sets the value of UserUUID.
func (s *Task) SetUserUUID(val OptUUID) {
	s.UserUUID = val
}

func (*Task) handleGetTaskRes() {}

type TaskStatus string

const (
	TaskStatusNew      TaskStatus = "new"
	TaskStatusFinished TaskStatus = "finished"
)

// AllValues returns all TaskStatus values.
func (TaskStatus) AllValues() []TaskStatus {
	return []TaskStatus{
		TaskStatusNew,
		TaskStatusFinished,
	}
}

// MarshalText implements encoding.TextMarshaler.
func (s TaskStatus) MarshalText() ([]byte, error) {
	switch s {
	case TaskStatusNew:
		return []byte(s), nil
	case TaskStatusFinished:
		return []byte(s), nil
	default:
		return nil, errors.Errorf("invalid value: %q", s)
	}
}

// UnmarshalText implements encoding.TextUnmarshaler.
func (s *TaskStatus) UnmarshalText(data []byte) error {
	switch TaskStatus(data) {
	case TaskStatusNew:
		*s = TaskStatusNew
		return nil
	case TaskStatusFinished:
		*s = TaskStatusFinished
		return nil
	default:
		return errors.Errorf("invalid value: %q", data)
	}
}
