// Code generated by ogen, DO NOT EDIT.

package api

import (
	"context"
)

// Handler handles operations described by OpenAPI v3 specification.
type Handler interface {
	// HandleCreateTask implements HandleCreateTask operation.
	//
	// Добавляет новую задачу.
	//
	// POST /task/create
	HandleCreateTask(ctx context.Context, req *Task) (HandleCreateTaskRes, error)
	// HandleDeleteTask implements HandleDeleteTask operation.
	//
	// Удалить задачу.
	//
	// DELETE /task/delete
	HandleDeleteTask(ctx context.Context, req *DeleteTaskRequest) (HandleDeleteTaskRes, error)
	// HandleFinishTask implements HandleFinishTask operation.
	//
	// Завершить задачу.
	//
	// PATCH /task/finish
	HandleFinishTask(ctx context.Context, req *FinishTaskRequest) (HandleFinishTaskRes, error)
	// HandleGetListOfTasks implements HandleGetListOfTasks operation.
	//
	// Получить список задач.
	//
	// GET /task/get_list
	HandleGetListOfTasks(ctx context.Context, req *GetListOfTasksRequest) (HandleGetListOfTasksRes, error)
	// HandleGetTask implements HandleGetTask operation.
	//
	// Получить задачу.
	//
	// GET /task/get
	HandleGetTask(ctx context.Context, req *GetTaskRequest) (HandleGetTaskRes, error)
}

// Server implements http server based on OpenAPI v3 specification and
// calls Handler to handle requests.
type Server struct {
	h Handler
	baseServer
}

// NewServer creates new Server.
func NewServer(h Handler, opts ...ServerOption) (*Server, error) {
	s, err := newServerConfig(opts...).baseServer()
	if err != nil {
		return nil, err
	}
	return &Server{
		h:          h,
		baseServer: s,
	}, nil
}
