// Code generated by ogen, DO NOT EDIT.

package openapi

// OperationName is the ogen operation name
type OperationName = string

const (
	HandleCreateTaskOperation     OperationName = "HandleCreateTask"
	HandleDeleteTaskOperation     OperationName = "HandleDeleteTask"
	HandleFinishTaskOperation     OperationName = "HandleFinishTask"
	HandleGetListOfTasksOperation OperationName = "HandleGetListOfTasks"
	HandleGetTaskOperation        OperationName = "HandleGetTask"
)
