// Code generated by ogen, DO NOT EDIT.

package api

import (
	"context"

	ht "github.com/ogen-go/ogen/http"
)

// UnimplementedHandler is no-op Handler which returns http.ErrNotImplemented.
type UnimplementedHandler struct{}

var _ Handler = UnimplementedHandler{}

// HandleCreateTask implements HandleCreateTask operation.
//
// Добавляет новую задачу.
//
// POST /task/create
func (UnimplementedHandler) HandleCreateTask(ctx context.Context, req *Task) (r HandleCreateTaskRes, _ error) {
	return r, ht.ErrNotImplemented
}

// HandleDeleteTask implements HandleDeleteTask operation.
//
// Удалить задачу.
//
// DELETE /task/delete
func (UnimplementedHandler) HandleDeleteTask(ctx context.Context, req *DeleteTaskRequest) (r HandleDeleteTaskRes, _ error) {
	return r, ht.ErrNotImplemented
}

// HandleFinishTask implements HandleFinishTask operation.
//
// Завершить задачу.
//
// PATCH /task/finish
func (UnimplementedHandler) HandleFinishTask(ctx context.Context, req *FinishTaskRequest) (r HandleFinishTaskRes, _ error) {
	return r, ht.ErrNotImplemented
}

// HandleGetListOfTasks implements HandleGetListOfTasks operation.
//
// Получить список задач.
//
// GET /task/get_list
func (UnimplementedHandler) HandleGetListOfTasks(ctx context.Context, req *GetListOfTasksRequest) (r HandleGetListOfTasksRes, _ error) {
	return r, ht.ErrNotImplemented
}

// HandleGetTask implements HandleGetTask operation.
//
// Получить задачу.
//
// GET /task/get
func (UnimplementedHandler) HandleGetTask(ctx context.Context, req *GetTaskRequest) (r HandleGetTaskRes, _ error) {
	return r, ht.ErrNotImplemented
}
