// Code generated by ogen, DO NOT EDIT.
package openapi

type HandleCreateTaskRes interface {
	handleCreateTaskRes()
}

type HandleDeleteTaskRes interface {
	handleDeleteTaskRes()
}

type HandleFinishTaskRes interface {
	handleFinishTaskRes()
}

type HandleGetListOfTasksRes interface {
	handleGetListOfTasksRes()
}

type HandleGetTaskRes interface {
	handleGetTaskRes()
}
