//go:build go1.22

// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.6.0 DO NOT EDIT.
package openapi

import (
	"context"
	"encoding/json"
	"fmt"
	"net/http"

	strictnethttp "github.com/oapi-codegen/runtime/strictmiddleware/nethttp"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Defines values for TaskStatusStatus.
const (
	Finished TaskStatusStatus = "finished"
	New      TaskStatusStatus = "new"
)

// Valid indicates whether the value is a known member of the TaskStatusStatus enum.
func (e TaskStatusStatus) Valid() bool {
	switch e {
	case Finished:
		return true
	case New:
		return true
	default:
		return false
	}
}

// CreateTaskRequest defines model for CreateTaskRequest.
type CreateTaskRequest struct {
	Description string             `json:"description"`
	Title       string             `json:"title"`
	UserUuid    openapi_types.UUID `json:"user_uuid"`
}

// CreateTaskResponse defines model for CreateTaskResponse.
type CreateTaskResponse struct {
	TaskUuid openapi_types.UUID `json:"task_uuid"`
}

// DeleteTaskRequest defines model for DeleteTaskRequest.
type DeleteTaskRequest struct {
	TaskUuid openapi_types.UUID `json:"task_uuid"`
	UserUuid openapi_types.UUID `json:"user_uuid"`
}

// Error defines model for Error.
type Error struct {
	Code    string `json:"code"`
	Message string `json:"message"`
}

// FinishTaskRequest defines model for FinishTaskRequest.
type FinishTaskRequest struct {
	TaskUuid openapi_types.UUID `json:"task_uuid"`
	UserUuid openapi_types.UUID `json:"user_uuid"`
}

// GetListOfTasksRequest defines model for GetListOfTasksRequest.
type GetListOfTasksRequest struct {
	UserUuid openapi_types.UUID `json:"user_uuid"`
}

// GetListOfTasksResponse defines model for GetListOfTasksResponse.
type GetListOfTasksResponse struct {
	Tasks []Task `json:"tasks"`
}

// GetTaskRequest defines model for GetTaskRequest.
type GetTaskRequest struct {
	TaskUuid openapi_types.UUID `json:"task_uuid"`
	UserUuid openapi_types.UUID `json:"user_uuid"`
}

// GetTaskResponse defines model for GetTaskResponse.
type GetTaskResponse struct {
	Description string     `json:"description"`
	Status      TaskStatus `json:"status"`
	Title       string     `json:"title"`
}

// Task defines model for Task.
type Task struct {
	Description *string     `json:"description,omitempty"`
	Status      *TaskStatus `json:"status,omitempty"`
	Title       *string     `json:"title,omitempty"`
}

// TaskStatus defines model for TaskStatus.
type TaskStatus struct {
	Status *TaskStatusStatus `json:"status,omitempty"`
}

// TaskStatusStatus defines model for TaskStatus.Status.
type TaskStatusStatus string

// BadRequest defines model for BadRequest.
type BadRequest = Error

// InternalError defines model for InternalError.
type InternalError = Error

// NotFound defines model for NotFound.
type NotFound = Error

// HandleCreateTaskJSONRequestBody defines body for HandleCreateTask for application/json ContentType.
type HandleCreateTaskJSONRequestBody = CreateTaskRequest

// HandleDeleteTaskJSONRequestBody defines body for HandleDeleteTask for application/json ContentType.
type HandleDeleteTaskJSONRequestBody = DeleteTaskRequest

// HandleFinishTaskJSONRequestBody defines body for HandleFinishTask for application/json ContentType.
type HandleFinishTaskJSONRequestBody = FinishTaskRequest

// HandleGetTaskJSONRequestBody defines body for HandleGetTask for application/json ContentType.
type HandleGetTaskJSONRequestBody = GetTaskRequest

// HandleGetListOfTasksJSONRequestBody defines body for HandleGetListOfTasks for application/json ContentType.
type HandleGetListOfTasksJSONRequestBody = GetListOfTasksRequest

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Добавляет новую задачу
	// (POST /task/create)
	HandleCreateTask(w http.ResponseWriter, r *http.Request)
	// Удалить задачу
	// (DELETE /task/delete)
	HandleDeleteTask(w http.ResponseWriter, r *http.Request)
	// Завершить задачу
	// (PATCH /task/finish)
	HandleFinishTask(w http.ResponseWriter, r *http.Request)
	// Получить задачу
	// (GET /task/get)
	HandleGetTask(w http.ResponseWriter, r *http.Request)
	// Получить список задач
	// (GET /task/get_list)
	HandleGetListOfTasks(w http.ResponseWriter, r *http.Request)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// HandleCreateTask operation middleware
func (siw *ServerInterfaceWrapper) HandleCreateTask(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.HandleCreateTask(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// HandleDeleteTask operation middleware
func (siw *ServerInterfaceWrapper) HandleDeleteTask(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.HandleDeleteTask(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// HandleFinishTask operation middleware
func (siw *ServerInterfaceWrapper) HandleFinishTask(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.HandleFinishTask(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// HandleGetTask operation middleware
func (siw *ServerInterfaceWrapper) HandleGetTask(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.HandleGetTask(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// HandleGetListOfTasks operation middleware
func (siw *ServerInterfaceWrapper) HandleGetListOfTasks(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.HandleGetListOfTasks(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{})
}

// ServeMux is an abstraction of http.ServeMux.
type ServeMux interface {
	HandleFunc(pattern string, handler func(http.ResponseWriter, *http.Request))
	ServeHTTP(w http.ResponseWriter, r *http.Request)
}

type StdHTTPServerOptions struct {
	BaseURL          string
	BaseRouter       ServeMux
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, m ServeMux) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseRouter: m,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, m ServeMux, baseURL string) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseURL:    baseURL,
		BaseRouter: m,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options StdHTTPServerOptions) http.Handler {
	m := options.BaseRouter

	if m == nil {
		m = http.NewServeMux()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	m.HandleFunc("POST "+options.BaseURL+"/task/create", wrapper.HandleCreateTask)
	m.HandleFunc("DELETE "+options.BaseURL+"/task/delete", wrapper.HandleDeleteTask)
	m.HandleFunc("PATCH "+options.BaseURL+"/task/finish", wrapper.HandleFinishTask)
	m.HandleFunc("GET "+options.BaseURL+"/task/get", wrapper.HandleGetTask)
	m.HandleFunc("GET "+options.BaseURL+"/task/get_list", wrapper.HandleGetListOfTasks)

	return m
}

type BadRequestJSONResponse Error

type InternalErrorJSONResponse Error

type NotFoundJSONResponse Error

type HandleCreateTaskRequestObject struct {
	Body *HandleCreateTaskJSONRequestBody
}

type HandleCreateTaskResponseObject interface {
	VisitHandleCreateTaskResponse(w http.ResponseWriter) error
}

type HandleCreateTask201JSONResponse CreateTaskResponse

func (response HandleCreateTask201JSONResponse) VisitHandleCreateTaskResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)

	return json.NewEncoder(w).Encode(response)
}

type HandleCreateTask400JSONResponse struct{ BadRequestJSONResponse }

func (response HandleCreateTask400JSONResponse) VisitHandleCreateTaskResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type HandleCreateTask500JSONResponse struct{ InternalErrorJSONResponse }

func (response HandleCreateTask500JSONResponse) VisitHandleCreateTaskResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type HandleDeleteTaskRequestObject struct {
	Body *HandleDeleteTaskJSONRequestBody
}

type HandleDeleteTaskResponseObject interface {
	VisitHandleDeleteTaskResponse(w http.ResponseWriter) error
}

type HandleDeleteTask204Response struct {
}

func (response HandleDeleteTask204Response) VisitHandleDeleteTaskResponse(w http.ResponseWriter) error {
	w.WriteHeader(204)
	return nil
}

type HandleDeleteTask400JSONResponse struct{ BadRequestJSONResponse }

func (response HandleDeleteTask400JSONResponse) VisitHandleDeleteTaskResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type HandleDeleteTask404JSONResponse struct{ NotFoundJSONResponse }

func (response HandleDeleteTask404JSONResponse) VisitHandleDeleteTaskResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type HandleDeleteTask500JSONResponse struct{ InternalErrorJSONResponse }

func (response HandleDeleteTask500JSONResponse) VisitHandleDeleteTaskResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type HandleFinishTaskRequestObject struct {
	Body *HandleFinishTaskJSONRequestBody
}

type HandleFinishTaskResponseObject interface {
	VisitHandleFinishTaskResponse(w http.ResponseWriter) error
}

type HandleFinishTask204Response struct {
}

func (response HandleFinishTask204Response) VisitHandleFinishTaskResponse(w http.ResponseWriter) error {
	w.WriteHeader(204)
	return nil
}

type HandleFinishTask400JSONResponse struct{ BadRequestJSONResponse }

func (response HandleFinishTask400JSONResponse) VisitHandleFinishTaskResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type HandleFinishTask404JSONResponse struct{ NotFoundJSONResponse }

func (response HandleFinishTask404JSONResponse) VisitHandleFinishTaskResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type HandleFinishTask500JSONResponse struct{ InternalErrorJSONResponse }

func (response HandleFinishTask500JSONResponse) VisitHandleFinishTaskResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type HandleGetTaskRequestObject struct {
	Body *HandleGetTaskJSONRequestBody
}

type HandleGetTaskResponseObject interface {
	VisitHandleGetTaskResponse(w http.ResponseWriter) error
}

type HandleGetTask200JSONResponse GetTaskResponse

func (response HandleGetTask200JSONResponse) VisitHandleGetTaskResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type HandleGetTask400JSONResponse struct{ BadRequestJSONResponse }

func (response HandleGetTask400JSONResponse) VisitHandleGetTaskResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type HandleGetTask404JSONResponse struct{ NotFoundJSONResponse }

func (response HandleGetTask404JSONResponse) VisitHandleGetTaskResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type HandleGetTask500JSONResponse struct{ InternalErrorJSONResponse }

func (response HandleGetTask500JSONResponse) VisitHandleGetTaskResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type HandleGetListOfTasksRequestObject struct {
	Body *HandleGetListOfTasksJSONRequestBody
}

type HandleGetListOfTasksResponseObject interface {
	VisitHandleGetListOfTasksResponse(w http.ResponseWriter) error
}

type HandleGetListOfTasks200JSONResponse GetListOfTasksResponse

func (response HandleGetListOfTasks200JSONResponse) VisitHandleGetListOfTasksResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type HandleGetListOfTasks400JSONResponse struct{ BadRequestJSONResponse }

func (response HandleGetListOfTasks400JSONResponse) VisitHandleGetListOfTasksResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type HandleGetListOfTasks404JSONResponse struct{ NotFoundJSONResponse }

func (response HandleGetListOfTasks404JSONResponse) VisitHandleGetListOfTasksResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type HandleGetListOfTasks500JSONResponse struct{ InternalErrorJSONResponse }

func (response HandleGetListOfTasks500JSONResponse) VisitHandleGetListOfTasksResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// Добавляет новую задачу
	// (POST /task/create)
	HandleCreateTask(ctx context.Context, request HandleCreateTaskRequestObject) (HandleCreateTaskResponseObject, error)
	// Удалить задачу
	// (DELETE /task/delete)
	HandleDeleteTask(ctx context.Context, request HandleDeleteTaskRequestObject) (HandleDeleteTaskResponseObject, error)
	// Завершить задачу
	// (PATCH /task/finish)
	HandleFinishTask(ctx context.Context, request HandleFinishTaskRequestObject) (HandleFinishTaskResponseObject, error)
	// Получить задачу
	// (GET /task/get)
	HandleGetTask(ctx context.Context, request HandleGetTaskRequestObject) (HandleGetTaskResponseObject, error)
	// Получить список задач
	// (GET /task/get_list)
	HandleGetListOfTasks(ctx context.Context, request HandleGetListOfTasksRequestObject) (HandleGetListOfTasksResponseObject, error)
}

type StrictHandlerFunc = strictnethttp.StrictHTTPHandlerFunc
type StrictMiddlewareFunc = strictnethttp.StrictHTTPMiddlewareFunc

type StrictHTTPServerOptions struct {
	RequestErrorHandlerFunc  func(w http.ResponseWriter, r *http.Request, err error)
	ResponseErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: StrictHTTPServerOptions{
		RequestErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		},
		ResponseErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		},
	}}
}

func NewStrictHandlerWithOptions(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc, options StrictHTTPServerOptions) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: options}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
	options     StrictHTTPServerOptions
}

// HandleCreateTask operation middleware
func (sh *strictHandler) HandleCreateTask(w http.ResponseWriter, r *http.Request) {
	var request HandleCreateTaskRequestObject

	var body HandleCreateTaskJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.HandleCreateTask(ctx, request.(HandleCreateTaskRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "HandleCreateTask")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(HandleCreateTaskResponseObject); ok {
		if err := validResponse.VisitHandleCreateTaskResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// HandleDeleteTask operation middleware
func (sh *strictHandler) HandleDeleteTask(w http.ResponseWriter, r *http.Request) {
	var request HandleDeleteTaskRequestObject

	var body HandleDeleteTaskJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.HandleDeleteTask(ctx, request.(HandleDeleteTaskRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "HandleDeleteTask")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(HandleDeleteTaskResponseObject); ok {
		if err := validResponse.VisitHandleDeleteTaskResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// HandleFinishTask operation middleware
func (sh *strictHandler) HandleFinishTask(w http.ResponseWriter, r *http.Request) {
	var request HandleFinishTaskRequestObject

	var body HandleFinishTaskJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.HandleFinishTask(ctx, request.(HandleFinishTaskRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "HandleFinishTask")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(HandleFinishTaskResponseObject); ok {
		if err := validResponse.VisitHandleFinishTaskResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// HandleGetTask operation middleware
func (sh *strictHandler) HandleGetTask(w http.ResponseWriter, r *http.Request) {
	var request HandleGetTaskRequestObject

	var body HandleGetTaskJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.HandleGetTask(ctx, request.(HandleGetTaskRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "HandleGetTask")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(HandleGetTaskResponseObject); ok {
		if err := validResponse.VisitHandleGetTaskResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// HandleGetListOfTasks operation middleware
func (sh *strictHandler) HandleGetListOfTasks(w http.ResponseWriter, r *http.Request) {
	var request HandleGetListOfTasksRequestObject

	var body HandleGetListOfTasksJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.HandleGetListOfTasks(ctx, request.(HandleGetListOfTasksRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "HandleGetListOfTasks")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(HandleGetListOfTasksResponseObject); ok {
		if err := validResponse.VisitHandleGetListOfTasksResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}
