// Code generated by mockery v2.53.6. DO NOT EDIT.

package task

import (
	context "context"
	entity "todo-backend/internal/entity"

	mock "github.com/stretchr/testify/mock"
)

// TaskService is an autogenerated mock type for the TaskService type
type TaskService struct {
	mock.Mock
}

// CreateTask provides a mock function with given fields: ctx, task
func (_m *TaskService) CreateTask(ctx context.Context, task entity.Task) (string, error) {
	ret := _m.Called(ctx, task)

	if len(ret) == 0 {
		panic("no return value specified for CreateTask")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, entity.Task) (string, error)); ok {
		return rf(ctx, task)
	}
	if rf, ok := ret.Get(0).(func(context.Context, entity.Task) string); ok {
		r0 = rf(ctx, task)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, entity.Task) error); ok {
		r1 = rf(ctx, task)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// DeleteTask provides a mock function with given fields: ctx, ID, userID
func (_m *TaskService) DeleteTask(ctx context.Context, ID string, userID string) error {
	ret := _m.Called(ctx, ID, userID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteTask")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = rf(ctx, ID, userID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// FinishTask provides a mock function with given fields: ctx, taskID, userID
func (_m *TaskService) FinishTask(ctx context.Context, taskID string, userID string) error {
	ret := _m.Called(ctx, taskID, userID)

	if len(ret) == 0 {
		panic("no return value specified for FinishTask")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = rf(ctx, taskID, userID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetListOfTasks provides a mock function with given fields: ctx, userID
func (_m *TaskService) GetListOfTasks(ctx context.Context, userID string) ([]entity.Task, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetListOfTasks")
	}

	var r0 []entity.Task
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) ([]entity.Task, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) []entity.Task); ok {
		r0 = rf(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entity.Task)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetTask provides a mock function with given fields: ctx, taskUUID, userUUID
func (_m *TaskService) GetTask(ctx context.Context, taskUUID string, userUUID string) (entity.Task, error) {
	ret := _m.Called(ctx, taskUUID, userUUID)

	if len(ret) == 0 {
		panic("no return value specified for GetTask")
	}

	var r0 entity.Task
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (entity.Task, error)); ok {
		return rf(ctx, taskUUID, userUUID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) entity.Task); ok {
		r0 = rf(ctx, taskUUID, userUUID)
	} else {
		r0 = ret.Get(0).(entity.Task)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, taskUUID, userUUID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewTaskService creates a new instance of TaskService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewTaskService(t interface {
	mock.TestingT
	Cleanup(func())
}) *TaskService {
	mock := &TaskService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
